receivers:
  otlp:
    protocols:
      grpc:
      http:

# exporters:  logzio:    account_token: "<<TRACING-SHIPPING-TOKEN>>"
#   #region: "<<LOGZIO_ACCOUNT_REGION_CODE>>" - (Optional)
exporters:
  debug:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true

processors:
  batch:

# extensions:
#   pprof:
#     endpoint: :1777
#     zpages:
#       endpoint: :55679
#     health_check:
extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/prometheus, debug]
  telemetry:
    logs:
      level: "debug"
